_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.18.1
            "6": 4.44.2
            "8":
                - 5
            "12": 0.18.1
            "13": darwin-arm64
batch_size:
    value: 32
best_model_path:
    value: ./models/experiment_1/best_model
epochs:
    value: 10
learning_rate:
    value: "2e-5"
max_length:
    value: 512
model_name:
    value: microsoft/deberta-v3-base
padding:
    value: longest
patience:
    value: 2
stride:
    value: 128
weight_decay:
    value: 0.001
